/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FramePrincipal.java
 *
 * Created on 15/07/2012, 06:21:34 PM
 */
package frames;

import clases.DBConnect;
import java.awt.Cursor;
import java.awt.Dialog;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Edgar
 */
public class FramePrincipal extends javax.swing.JFrame {
    private Image imagen = getToolkit().getImage(getClass().getResource("/imagenes/global2.png"));
    private int i=0;
    private DBConnect db;
    private double zoom=1.0;
    private String ruta="";
    private jDProductos a;
    private jDClientes b;
    private JDProveedor c;
    private jDVentas d;
    private jDPresupuestos e;
    private jDCompras f;
    private jDGastos g;
    private boolean botonCompra=true;
    /** Creates new form FramePrincipal */
    public FramePrincipal() {
        initComponents();
        this.setIconImage(imagen); 
        setLocationRelativeTo(null);
        db=new DBConnect();
        db.conectado();
        
        a = new jDProductos(this, true,db);
        b = new jDClientes(this, true, db);
        c = new JDProveedor(this, true, db,0);
        d = new jDVentas(this, true, db);
        e = new jDPresupuestos(this, true, db);
        f = new jDCompras(this, true, db);
        g = new jDGastos(this, true, db);
  
        a.setPreferredSize(a.getMaximumSize());
        
        this.setTitle("ControlSoft - MB Importaciones S.R.L.");
 }
 

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPImagen = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPBotones = new javax.swing.JPanel();
        jBProductos = new javax.swing.JButton();
        jBPacientes = new javax.swing.JButton();
        jBVendedor = new javax.swing.JButton();
        jBVentas = new javax.swing.JButton();
        jBPresup = new javax.swing.JButton();
        jBCompra = new javax.swing.JButton();
        jBGastos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        JMReports = new javax.swing.JMenu();
        jMVentas = new javax.swing.JMenu();
        jMVentsDias = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/shutdown.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPImagenLayout = new javax.swing.GroupLayout(jPImagen);
        jPImagen.setLayout(jPImagenLayout);
        jPImagenLayout.setHorizontalGroup(
            jPImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPImagenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPImagenLayout.setVerticalGroup(
            jPImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPImagenLayout.createSequentialGroup()
                .addContainerGap(430, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPBotones.setLayout(new java.awt.GridLayout(1, 7, 10, 0));

        jBProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Products_32x32.png"))); // NOI18N
        jBProductos.setText("Productos");
        jBProductos.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jBProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProductosActionPerformed(evt);
            }
        });
        jBProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBProductosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBProductosKeyReleased(evt);
            }
        });
        jPBotones.add(jBProductos);

        jBPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Clientes_32x32.png"))); // NOI18N
        jBPacientes.setText("Clientes");
        jBPacientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBPacientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPacientesActionPerformed(evt);
            }
        });
        jBPacientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBPacientesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBPacientesKeyReleased(evt);
            }
        });
        jPBotones.add(jBPacientes);

        jBVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vendedor_32x32.png"))); // NOI18N
        jBVendedor.setText("Proveedores");
        jBVendedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBVendedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVendedorActionPerformed(evt);
            }
        });
        jBVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBVendedorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBVendedorKeyReleased(evt);
            }
        });
        jPBotones.add(jBVendedor);

        jBVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ventas_32x32.png"))); // NOI18N
        jBVentas.setText("Ventas");
        jBVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVentasActionPerformed(evt);
            }
        });
        jBVentas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBVentasKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBVentasKeyReleased(evt);
            }
        });
        jPBotones.add(jBVentas);

        jBPresup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon_presupuesto.png"))); // NOI18N
        jBPresup.setText("Presupuesto");
        jBPresup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBPresup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBPresup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPresupActionPerformed(evt);
            }
        });
        jBPresup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBPresupKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBPresupKeyReleased(evt);
            }
        });
        jPBotones.add(jBPresup);

        jBCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clipboard.png"))); // NOI18N
        jBCompra.setText("Compra");
        jBCompra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCompra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCompraActionPerformed(evt);
            }
        });
        jBCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBCompraKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBCompraKeyReleased(evt);
            }
        });
        jPBotones.add(jBCompra);

        jBGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clipboard.png"))); // NOI18N
        jBGastos.setText("Gastos");
        jBGastos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBGastos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGastosActionPerformed(evt);
            }
        });
        jPBotones.add(jBGastos);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ventas_32x32.png"))); // NOI18N
        jButton2.setText("Ventas por Categoria");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPBotones.add(jButton2);

        jMenuBar1.setAlignmentX(240.0F);

        jMenu2.setText("Bancos");

        jMenuItem6.setText("Agregar Banco");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Empresas");

        jMenuItem7.setText("Lista");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        JMReports.setText("Reportes");

        jMVentas.setText("Ventas");

        jMVentsDias.setText("Ventas Diarias");
        jMVentsDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVentsDiasActionPerformed(evt);
            }
        });
        jMVentas.add(jMVentsDias);

        jMenuItem4.setText("Ventas vs Compra");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMVentas.add(jMenuItem4);

        JMReports.add(jMVentas);

        jMenu1.setText("Productos");

        jMenuItem1.setText("Mayor Rotación Según Volumen");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Mayor Rotación Según Utilidad");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Productos Sin Movimiento");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        JMReports.add(jMenu1);

        jMenuBar1.add(JMReports);

        jMenu3.setText("Configuraciones");

        jMenuItem5.setText("Visualizar Boton Compra");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMayuda.setMnemonic('A');
        jMayuda.setText("Ayuda");
        jMayuda.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMayudaMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenuBar1.add(jMayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 1438, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*

    private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
        // TODO add your handling code here:
        int w=jPImagen.getWidth();
        int h=jPImagen.getHeight();
        mipanel pp = new mipanel(w,h);
        jPImagen.add(pp);
        jPImagen.repaint();
    }                                    

     */
    private void jBProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProductosActionPerformed
            
            a.setVisible(true);
    }//GEN-LAST:event_jBProductosActionPerformed

    private void jBPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPacientesActionPerformed
            b.setVisible(true);
    }//GEN-LAST:event_jBPacientesActionPerformed

    private void jBVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVendedorActionPerformed
            c.setVisible(true);
    }//GEN-LAST:event_jBVendedorActionPerformed

    private void jBVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVentasActionPerformed
          d.setVisible(true);
    }//GEN-LAST:event_jBVentasActionPerformed

    private void jBCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCompraActionPerformed
        
          f.setVisible(true);
    }//GEN-LAST:event_jBCompraActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        db.desconectar(); 
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMayudaMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMayudaMenuKeyPressed
        
    }//GEN-LAST:event_jMayudaMenuKeyPressed

    private void jBProductosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBProductosKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            jBPacientes.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            jBCompra.requestFocus();
        }
    }//GEN-LAST:event_jBProductosKeyPressed

    private void jBPacientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBPacientesKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            jBVendedor.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            jBProductos.requestFocus();
        }
    }//GEN-LAST:event_jBPacientesKeyPressed

    private void jBVendedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBVendedorKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            jBVentas.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            jBPacientes.requestFocus();
        }
    }//GEN-LAST:event_jBVendedorKeyPressed

    private void jBVentasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBVentasKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            jBPresup.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            jBVendedor.requestFocus();
        }
    }//GEN-LAST:event_jBVentasKeyPressed

    private void jBCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBCompraKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            jBProductos.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            jBPresup.requestFocus();
        }
    }//GEN-LAST:event_jBCompraKeyPressed

    private void jMVentsDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVentsDiasActionPerformed
        jDViewDate a = new jDViewDate(this, true,"Seleccione una Fecha:");
        a.setVisible(true);
        ResultSet r=null;
        if(a.fecha!=null){
            
         try{
           r=db.Listar("*", "vistaventa", "where `Fecha_venta` >= '"+(a.fecha.getYear()+1900)+"-"
                   +(a.fecha.getMonth()+1)+"-"+(a.fecha.getDate())+"' order by Id_venta ASC");
          

           
        } catch (Exception ex) {
             //Logger.getLogger(ciudad.class.getName()).log(Level.SEVERE, null, ex);
        }

        JRResultSetDataSource jrRS = new JRResultSetDataSource(r);
        HashMap parameters = new HashMap();
        
        try{
            URL urlMaestro = getClass().getClassLoader().getResource("reportes/Ventas.jasper");
            // Cargamos el reporte
            JasperReport masterReport = null;
            masterReport = (JasperReport) JRLoader.loadObject(urlMaestro);
            JasperPrint masterPrint = null;
            masterPrint = JasperFillManager.fillReport(masterReport,parameters,jrRS);
               
            
            
             JasperViewer ventana = new JasperViewer(masterPrint,false);
            ventana.setTitle("Vista Previa");
            ventana.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
            ventana.setVisible(true);

        }catch(JRException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocurrio un error "+e.toString(),"ATENCION ", JOptionPane.INFORMATION_MESSAGE);
        }
    }                                        

     
        
    }//GEN-LAST:event_jMVentsDiasActionPerformed

    private void jBProductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBProductosKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_P){
            
            jBVendedor.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_C){
            jBPacientes.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_V){
            jBVentas.requestFocus();
        }
    }//GEN-LAST:event_jBProductosKeyReleased

    private void jBPacientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBPacientesKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_P){
            
            jBVendedor.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_C){
            jBCompra.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_V){
            jBVentas.requestFocus();
        }
    }//GEN-LAST:event_jBPacientesKeyReleased

    private void jBVendedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBVendedorKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_P){
            
            jBPresup.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_C){
            jBCompra.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_V){
            jBVentas.requestFocus();
        }
    }//GEN-LAST:event_jBVendedorKeyReleased

    private void jBVentasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBVentasKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_P){
            
            jBPresup.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_C){
            jBCompra.requestFocus();
        }
        
       
    }//GEN-LAST:event_jBVentasKeyReleased

    private void jBCompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBCompraKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_P){
            
            jBProductos.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_C){
            jBPacientes.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_V){
            jBVentas.requestFocus();
        }
    }//GEN-LAST:event_jBCompraKeyReleased

    private void jBPresupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPresupActionPerformed
        e.setVisible(true);
    }//GEN-LAST:event_jBPresupActionPerformed

    private void jBPresupKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBPresupKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            jBCompra.requestFocus();
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            jBVentas.requestFocus();
        }
    }//GEN-LAST:event_jBPresupKeyPressed

    private void jBPresupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBPresupKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_P){
            
            jBProductos.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_C){
            jBCompra.requestFocus();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_V){
            jBVentas.requestFocus();
        }
    }//GEN-LAST:event_jBPresupKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        /*consulto por el rango de fechas para el reporte */
        
        jDSeleccionPrecio jDTipoPrecio = new jDSeleccionPrecio(this, true);
        jDTipoPrecio.setVisible(true);
        
        String tipoPrecio = jDTipoPrecio.getPrecio();
        
        if(tipoPrecio.equals("Precio 1"))
            tipoPrecio="pre_venta1";
        else if(tipoPrecio.equals("Precio 2"))
            tipoPrecio="pre_venta2";
        else if(tipoPrecio.equals("Precio 3"))
            tipoPrecio="pre_venta3";
        else if(tipoPrecio.equals("Precio 4"))
            tipoPrecio="pre_venta4";
        else if(tipoPrecio.equals("Modificado por Usuario"))
            tipoPrecio="pre_n_venta";
        else
            tipoPrecio="todos";
        Date date = new Date();
        int mes = date.getMonth();
        if(mes==0){
            mes=12;
            date.setYear(date.getYear()-1);
        }else{
            mes-=1;
        }
        date.setMonth(mes);
        jDViewDate a = new jDViewDate(this, true,"Seleccione una fecha de inicio:");
        a.setFecha(date);
        a.setVisible(true);
        
        jDViewDate b = new jDViewDate(this, true,"Seleccione una fecha de fin:");
        b.setFecha(new Date());
        b.setVisible(true);
        
        Date desde,hasta;
        desde = a.fecha;
        hasta = b.fecha;
        
        if(!tipoPrecio.equals("todos")){
            generarReporte(jDTipoPrecio, tipoPrecio, "volumen",desde,hasta);
        }else{
            jDTipoPrecio.setSelection(0);
            generarReporte(jDTipoPrecio, "pre_venta1", "volumen",desde,hasta);
            jDTipoPrecio.setSelection(1);
            generarReporte(jDTipoPrecio, "pre_venta2", "volumen",desde,hasta);
            jDTipoPrecio.setSelection(2);
            generarReporte(jDTipoPrecio, "pre_venta3", "volumen",desde,hasta);
            jDTipoPrecio.setSelection(3);
            generarReporte(jDTipoPrecio, "pre_venta4", "volumen",desde,hasta);
            jDTipoPrecio.setSelection(4);
            generarReporte(jDTipoPrecio, "pre_n_venta", "volumen",desde,hasta);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void generarReporte(jDSeleccionPrecio jDTipoPrecio,String tipoPrecio,String tipoReporte,Date a,Date b){
        
        String sOrderBy;
        if(tipoReporte.equals("volumen"))
            sOrderBy="cuenta";
        else
            sOrderBy="SubTotal";
        
        ResultSet rs = null;
            rs=db.Listar("DISTINCT `producto`.`Cod_inter_producto`,`Marca_Fabrica`,`Cod_Original`,`Nom_producto`,`Marca_producto`,`detalle_producto`,`ubica_producto`,`precio_n_venta`,`Cant_producto`,`cant_min`,`pre_compra`,`Proveedor_Id_proveedor`,`ultima_venta`,`imagen`,`ruta_imagen`"
                    + " ,COUNT(*)  AS cuenta ,SUM(precio_n_venta*Cant_vendida) AS SubTotal,SUM(`detalle_venta`.`Cant_vendida`) AS CantVendida",
                    "detalle_venta,producto,venta",
                    "where `producto`.`Cod_inter_producto`=`detalle_venta`.`Cod_inter_producto` and `venta`.`Id_venta`=`detalle_venta`.`Venta_Id_venta` and `Fecha_venta` >= '"+(a.getYear()+1900)+"-"
                      +(a.getMonth()+1)+"-"+(a.getDate())+"' and `Fecha_venta` <= '"+(b.getYear()+1900)+"-" 
                      +(b.getMonth()+1)+"-"+(b.getDate())+"' and `detalle_venta`.`nro_precio`= '"+tipoPrecio+"' group by `producto`.`Cod_inter_producto` order by "+sOrderBy+" DESC limit 30");


            JRResultSetDataSource jrRS = new JRResultSetDataSource(rs);
            HashMap parameters = new HashMap();
            parameters.clear();

            parameters.put("TipoReporte", tipoReporte);
            parameters.put("TipoPrecio",jDTipoPrecio.getPrecio());
            try{
                this.setCursor(Cursor.WAIT_CURSOR);
                URL urlMaestro = getClass().getClassLoader().getResource("reportes/ProductoRotacionReport.jasper");
                JasperReport masterReport = null;
                masterReport = (JasperReport) JRLoader.loadObject(urlMaestro);
                JasperPrint masterPrint = null;
                masterPrint = JasperFillManager.fillReport(masterReport,parameters,jrRS);
                JasperViewer ventana = new JasperViewer(masterPrint,false);
                ventana.setTitle("Vista Previa");
                ventana.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
                ventana.setVisible(true);
                this.setCursor(null);
            }catch(JRException e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Ocurrio un error "+e.toString(),"ATENCION ", JOptionPane.INFORMATION_MESSAGE);
            }
            jDTipoPrecio.dispose();
    }
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jDSeleccionPrecio jDTipoPrecio = new jDSeleccionPrecio(this, true);
        jDTipoPrecio.setVisible(true);
        
        String tipoPrecio = jDTipoPrecio.getPrecio();
        
        if(tipoPrecio.equals("Precio 1"))
            tipoPrecio="pre_venta1";
        else if(tipoPrecio.equals("Precio 2"))
            tipoPrecio="pre_venta2";
        else if(tipoPrecio.equals("Precio 3"))
            tipoPrecio="pre_venta3";
        else if(tipoPrecio.equals("Precio 4"))
            tipoPrecio="pre_venta4";
        else if(tipoPrecio.equals("Modificado por Usuario"))
            tipoPrecio="pre_n_venta";
        else
            tipoPrecio="todos";
        Date date = new Date();
        int mes = date.getMonth();
        if(mes==0){
            mes=12;
            date.setYear(date.getYear()-1);
        }else{
            mes-=1;
        }
        date.setMonth(mes);
        jDViewDate a = new jDViewDate(this, true,"Seleccione una fecha de inicio:");
        a.setFecha(date);
        a.setVisible(true);
        
        jDViewDate b = new jDViewDate(this, true,"Seleccione una fecha de fin:");
        b.setFecha(new Date());
        b.setVisible(true);
        
        Date desde,hasta;
        
        desde = a.fecha;
        hasta = b.fecha;
        
        if(!tipoPrecio.equals("todos")){
            generarReporte(jDTipoPrecio, tipoPrecio, "utilidad",desde,hasta);
        }else{
            jDTipoPrecio.setSelection(0);
            generarReporte(jDTipoPrecio, "pre_venta1", "utilidad",desde,hasta);
            jDTipoPrecio.setSelection(1);
            generarReporte(jDTipoPrecio, "pre_venta2", "utilidad",desde,hasta);
            jDTipoPrecio.setSelection(2);
            generarReporte(jDTipoPrecio, "pre_venta3", "utilidad",desde,hasta);
            jDTipoPrecio.setSelection(3);
            generarReporte(jDTipoPrecio, "pre_venta4", "utilidad",desde,hasta);
            jDTipoPrecio.setSelection(4);
            generarReporte(jDTipoPrecio, "pre_n_venta", "utilidad",desde,hasta);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ResultSet r=null;
        
        Date hoy = new Date();
        int mes=hoy.getMonth()+1;
        if(mes<=6){
            mes+=6;
            hoy.setYear(hoy.getYear()-1);
        }else{
            mes-=6;
        }
        String sHoy = (hoy.getYear()+1900)+"/"+mes+"/"+hoy.getDate();
        
        try{
        
      
            r=db.Listar("*", "producto,proveedor", " where `producto`.`Proveedor_Id_proveedor`=`proveedor`.`Id_proveedor` and (ultima_venta < '"+sHoy+"')");
        } catch (Exception ex) {
             //Logger.getLogger(ciudad.class.getName()).log(Level.SEVERE, null, ex);
        }

        JRResultSetDataSource jrRS = new JRResultSetDataSource(r);
        HashMap parameters = new HashMap();
        parameters.put("titulo", "Productos sin Movimiento por más de 6 meses");
        try{
            int resp = JOptionPane.showConfirmDialog(rootPane, "¿Deséa que el listado de productos contenga imágenes?", "Productos con su imagen", JOptionPane.YES_NO_OPTION);
            URL urlMaestro;
            if(resp==JOptionPane.YES_OPTION)
                urlMaestro = getClass().getClassLoader().getResource("reportes/productosconimagen.jasper");
            else
                urlMaestro = getClass().getClassLoader().getResource("reportes/productos.jasper");
            // Cargamos el reporte
            JasperReport masterReport = null;
            masterReport = (JasperReport) JRLoader.loadObject(urlMaestro);
            JasperPrint masterPrint = null;
            masterPrint = JasperFillManager.fillReport(masterReport,parameters,jrRS);
               
                
             JasperViewer ventana = new JasperViewer(masterPrint,false);
            ventana.setTitle("Vista Previa");
            ventana.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
            ventana.setVisible(true);

        }catch(JRException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocurrio un error "+e.toString(),"ATENCION ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ResultSet r=null,r1= null,r2=null;
        
         Date hoy = new Date();
         String sHoy = (hoy.getYear()+1900)+"/"+(hoy.getMonth()+1)+"/"+hoy.getDate();
        int mes=hoy.getMonth()+1;
        if(mes==0){
            mes=12;
            hoy.setYear(hoy.getYear()-1);
        }else{
            mes-=1;
        }
        String sH1Mes = (hoy.getYear()+1900)+"/"+mes+"/"+hoy.getDate();
        
        try{
        
            r=db.Listar("*", "vistaUtilidad", "");
            r1=db.Listar("sum(pre_n_venta*cant_vendida)", "vistafactura", " where Fecha_venta >= '"+sH1Mes+"' and Fecha_venta <= '"+sHoy+"'");
            r2=db.Listar("sum(pre_compra*cant_adquirida)", "vistacompra3", " where Fecha_compra >= '"+sH1Mes+"' and Fecha_compra <= '"+sHoy+"'");
        } catch (Exception ex) {
             //Logger.getLogger(ciudad.class.getName()).log(Level.SEVERE, null, ex);
        }
        Integer subVenta=0,SubCompra=0;
        try {
            if(r1.next()){
                subVenta = r1.getInt(1);
            }
            if(r2.next()){
                SubCompra=r2.getInt(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JRResultSetDataSource jrRS = new JRResultSetDataSource(r);
        HashMap parameters = new HashMap();
        parameters.put("TotalVenta",subVenta);
        parameters.put("TotalCompra",SubCompra);
        try{
            URL urlMaestro;
            urlMaestro = getClass().getClassLoader().getResource("reportes/UtilidadIntento5.jasper");
            // Cargamos el reporte
            JasperReport masterReport = null;
            masterReport = (JasperReport) JRLoader.loadObject(urlMaestro);
            JasperPrint masterPrint = null;
            masterPrint = JasperFillManager.fillReport(masterReport,parameters,jrRS);
               
                
             JasperViewer ventana = new JasperViewer(masterPrint,false);
            ventana.setTitle("Vista Previa");
            ventana.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
            ventana.setVisible(true);

        }catch(JRException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocurrio un error "+e.toString(),"ATENCION ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new JDNewBank(this, true, db).setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if(botonCompra){
            jBCompra.setVisible(false);
            botonCompra=false;
        }else{
            jBCompra.setVisible(false);
            botonCompra=true;
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jBGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGastosActionPerformed
        g.setVisible(true);
    }//GEN-LAST:event_jBGastosActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        new jDListEmpresa(this, botonCompra, db).setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new jDVentasCategoria(this, false, db).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    public void habilitador(boolean ban){
        jBCompra.setVisible(ban);
        jBPacientes.setVisible(ban);
        jBPresup.setVisible(ban);
        jBProductos.setVisible(ban);
        jBVendedor.setVisible(ban);
        jBVentas.setVisible(ban);
    }
    
    
  
            /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
           

            @Override
            public void run() {
               try{
                   UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
               }catch(Exception e){
                   
               }
                new FramePrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMReports;
    private javax.swing.JButton jBCompra;
    private javax.swing.JButton jBGastos;
    private javax.swing.JButton jBPacientes;
    private javax.swing.JButton jBPresup;
    private javax.swing.JButton jBProductos;
    private javax.swing.JButton jBVendedor;
    private javax.swing.JButton jBVentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMVentas;
    private javax.swing.JMenuItem jMVentsDias;
    private javax.swing.JMenu jMayuda;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPBotones;
    private javax.swing.JPanel jPImagen;
    // End of variables declaration//GEN-END:variables
}
