/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import clases.DBConnect;
import java.awt.Image;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ever
 */
public class jDGastos extends javax.swing.JDialog {
     private static String vend;
    Image imagen = getToolkit().getImage(getClass().getResource("/imagenes/global2.png"));
    DBConnect bd;
    DefaultTableModel m;
    ResultSet r;
    private int i=0;
    private String hoy1;
    private String fecha1;
    Date hoy;
    Date fecha;
    DateFormat hola;
    /**
     * Creates new form jDGastos
     */
    public jDGastos(java.awt.Frame parent, boolean modal,DBConnect con) {
        super(parent, modal);
        initComponents();
        setIconImage(imagen);
        this.setLocationRelativeTo(null);
        this.setTitle("Gastos");
        hoy = new Date();
        hola = DateFormat.getDateInstance();
        hoy1 = hola.format(hoy);
        fecha = new Date();
        jXhasta.setDate(hoy);
        fecha.setMonth(hoy.getMonth()-1);
        jXdesde.setDate(fecha);
        bd = con;
        jBNueva.requestFocus();
        PrepararTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBotones = new javax.swing.JPanel();
        jBNueva = new javax.swing.JButton();
        jBImpreg = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jXhasta = new org.jdesktop.swingx.JXDatePicker();
        jXdesde = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jTUtilidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTVentas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPBotones.setLayout(new java.awt.GridLayout(1, 3));

        jBNueva.setText("Nuevo Gasto");
        jBNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevaActionPerformed(evt);
            }
        });
        jPBotones.add(jBNueva);

        jBImpreg.setText("Imprimir el registro");
        jBImpreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImpregActionPerformed(evt);
            }
        });
        jPBotones.add(jBImpreg);

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        jPBotones.add(jBSalir);

        jXhasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXhastaActionPerformed(evt);
            }
        });

        jXdesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXdesdeActionPerformed(evt);
            }
        });

        jLabel3.setText("al:");

        jLabel4.setText("Gasto Total:");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Visualizar las ventas correspondientes al periodo");

        jTVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro. De Gasto", "Fecha", "Observaciones", "Total Parcila de Gasto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTVentas.setColumnSelectionAllowed(true);
        jTVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTVentas);
        jTVentas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTVentas.getColumnModel().getColumn(0).setResizable(false);
        jTVentas.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTVentas.getColumnModel().getColumn(1).setResizable(false);
        jTVentas.getColumnModel().getColumn(2).setResizable(false);
        jTVentas.getColumnModel().getColumn(3).setResizable(false);

        jLabel5.setText("Gs.");

        jLabel2.setText("de:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                            .addComponent(jPBotones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXdesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXhasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jXhasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jXdesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
     private Integer CalcGastos(String Cod){
       ResultSet rS=null;
       rS= bd.Listar("*", "detalle_gasto", "where Id_gasto='"+Cod+"'");
       Integer gasto=0;
        try {
            while(rS.next()){
                gasto+=Integer.valueOf(rS.getString("monto"));
            }
         
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,ex.getMessage(),"Error 382", JOptionPane.ERROR_MESSAGE);
        }
        return gasto;
   }
    
    
    private void PrepararTabla() {
        int gastoTotal=0;
        r= null;
        r = bd.Listar("*", "gastos", "where `Fecha_gasto` >= '"+(fecha.getYear()+1900)+"-"+(fecha.getMonth()+1)+"-"+(fecha.getDate())+"' and Fecha_gasto <= '"+(hoy.getYear()+1900)+"-"+(hoy.getMonth()+1)+"-"+(hoy.getDate())+"' order by Id_gasto ASC");
        m= (new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Nro. De Gasto", "Fecha", "Observaciones", "Total Parcila de Gasto"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
        jTVentas.setModel(m);
        String Fila[]= new String[4];
            try {
                while(r.next()){
                    Fila[0]= r.getString("Id_gasto");
                    Fila[1]= r.getString("Fecha_gasto");
                    Fila[2]= r.getString("Obs_gasto");
                    Fila[3]= String.valueOf(CalcGastos(Fila[0]));
                    gastoTotal+=Integer.valueOf(Fila[3]);
                    m.addRow(Fila);
                }
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, ex.getMessage(),"Error1",JOptionPane.ERROR_MESSAGE);
            }
            
            jTUtilidad.setText(String.valueOf(gastoTotal));
            
        }
    
    private void jBNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevaActionPerformed
        // TODO add your handling code here:
        new jDNuevoGasto(null, true, bd).setVisible(true);
        PrepararTabla();

    }//GEN-LAST:event_jBNuevaActionPerformed

    private void jBImpregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImpregActionPerformed
        try{
            r=null;
            r=bd.Listar("`gastos`.*,SUM(`detalle_gasto`.`monto`) AS gastoTotal", "gastos,detalle_gasto", "where `gastos`.`Id_gasto`=`detalle_gasto`.`Id_gasto` and `Fecha_gasto` >= '"+(fecha.getYear()+1900)+"-"
                +(fecha.getMonth()+1)+"-"+(fecha.getDate())+"' and Fecha_gasto <= '"+(hoy.getYear()+1900)
                +"-"+(hoy.getMonth()+1)+"-"+(hoy.getDate())+"' order by Id_gasto ASC");

        } catch (Exception ex) {
            //Logger.getLogger(ciudad.class.getName()).log(Level.SEVERE, null, ex);
        }

        JRResultSetDataSource jrRS = new JRResultSetDataSource(r);
        HashMap parameters = new HashMap();

        try{
            URL urlMaestro = getClass().getClassLoader().getResource("reportes/Gastos.jasper");
            // Cargamos el reporte
            JasperReport masterReport = null;
            masterReport = (JasperReport) JRLoader.loadObject(urlMaestro);
            JasperPrint masterPrint = null;
            masterPrint = JasperFillManager.fillReport(masterReport,parameters,jrRS);

            JasperViewer ventana = new JasperViewer(masterPrint,false);
            ventana.setTitle("Vista Previa");
            ventana.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);
            ventana.setVisible(true);

        }catch(JRException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocurrio un error "+e.toString(),"ATENCION ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBImpregActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jXhastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXhastaActionPerformed
        // TODO add your handling code here:
        hoy= jXhasta.getDate();
        PrepararTabla();
    }//GEN-LAST:event_jXhastaActionPerformed

    private void jXdesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXdesdeActionPerformed
        // TODO add your handling code here:
        fecha= jXdesde.getDate();
        PrepararTabla();
    }//GEN-LAST:event_jXdesdeActionPerformed

    private void jTVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTVentasMouseClicked
        if(evt.getClickCount()==2){
        }
        if(evt.getButton()==evt.BUTTON3){
        }
    }//GEN-LAST:event_jTVentasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jDGastos dialog = new jDGastos(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBImpreg;
    private javax.swing.JButton jBNueva;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPBotones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTUtilidad;
    private javax.swing.JTable jTVentas;
    private org.jdesktop.swingx.JXDatePicker jXdesde;
    private org.jdesktop.swingx.JXDatePicker jXhasta;
    // End of variables declaration//GEN-END:variables
}
