/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import clases.DBConnect;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Ever
 */
public class JDNewBank extends javax.swing.JDialog {

    DBConnect db;
    /**
     * Creates new form JDNewBank
     */
    public JDNewBank(java.awt.Frame parent, boolean modal, DBConnect con) {
        super(parent, modal);
        this.setLocationRelativeTo(null);
        initComponents();
        this.db=con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jBCancelar = new javax.swing.JButton();
        jBAceptar = new javax.swing.JButton();
        jPformulario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTNomBanco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTPaís = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTCodBanco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtInstEsp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jXLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banco-icono-7880-128.png"))); // NOI18N

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBAceptar.setText("Guardar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        jPformulario.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Banco"));
        jPformulario.setLayout(new java.awt.GridLayout(5, 2, 10, 15));

        jLabel3.setText("Nombre del Banco:");
        jPformulario.add(jLabel3);

        jTNomBanco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTNomBancoKeyReleased(evt);
            }
        });
        jPformulario.add(jTNomBanco);

        jLabel9.setText("Ciudad/País:");
        jPformulario.add(jLabel9);
        jPformulario.add(jTPaís);

        jLabel7.setText("Código de Banco(ABA,FEDWIRE,SWIFT,CHIPS,OTROS):");
        jPformulario.add(jLabel7);
        jPformulario.add(jTCodBanco);

        jLabel2.setText("Instrucciones Especiales:");
        jPformulario.add(jLabel2);

        jtInstEsp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtInstEspKeyReleased(evt);
            }
        });
        jPformulario.add(jtInstEsp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPformulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPformulario, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar)
                    .addComponent(jBAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.dispose();

    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        if(!jTNomBanco.equals("")){
                if(db.Altas("banco", "(`nombre_banco`, `ciudadpais_banco`, `codigo_banco`, `espinstru_banco`)","('"+jTNomBanco.getText()+"','"+jTPaís.getText()+"','"+jTCodBanco.getText()+"','"+jtInstEsp.getText()+"');"))
                JOptionPane.showMessageDialog(rootPane, "El banco ha sido registrado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                else
                JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un error inesperado. Contacte con el Administrador del Sistema", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "El campo Ruc no debe estar vacío","Atencion",JOptionPane.ERROR_MESSAGE);
        }
        int resp = JOptionPane.showConfirmDialog(rootPane, "¿Desea terminar el registro de bancos?", "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(resp==JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_jBAceptarActionPerformed

    private void jtInstEspKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtInstEspKeyReleased
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_jtInstEspKeyReleased

    private void jTNomBancoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNomBancoKeyReleased
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_jTNomBancoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDNewBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDNewBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDNewBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDNewBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDNewBank dialog = new JDNewBank(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPformulario;
    private javax.swing.JTextField jTCodBanco;
    private javax.swing.JTextField jTNomBanco;
    private javax.swing.JTextField jTPaís;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private javax.swing.JTextField jtInstEsp;
    // End of variables declaration//GEN-END:variables
}
