/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jDnventa.java
 *
 * Created on 11/08/2012, 03:36:02 PM
 */
package frames;

import clases.DBConnect;
import clases.Numero_a_Letra;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JOptionPane;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Edgar
 */
public class jDnPresupuesto extends javax.swing.JDialog {
Image imagen = getToolkit().getImage(getClass().getResource("/imagenes/global2.png"));
DefaultTableModel m;
private  Numero_a_Letra NL = new  Numero_a_Letra();
private  String vendedor;
private  String password;
private String Host;
private String Puerto;
private String Database;
private DBConnect db;
private ResultSet r;
private int i=0;
private Date a;
private Integer total=0;
private Integer existencia=0;
private int nro =1;
private jDProductos prod;
private boolean ex= true;// controla si la existencia del producto es suficiente
/** Creates new form jDnventa */
    public jDnPresupuesto(java.awt.Frame parent, boolean modal,DBConnect con) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        db = con;
        jcNombre.setEditable(true);
        AutoCompleteDecorator.decorate(jcNombre);
        setIconImage(imagen);
        this.setTitle("Agregar Venta");
        actualizarCombo();
        a = new Date();
        jTFecha.setText(String.valueOf(a.getDate())+"/"+String.valueOf(a.getMonth()+1)+"/"+String.valueOf(a.getYear()+1900));
        jTFecha.setEditable(false);
        jTNumPresup.setEditable(false);
        String titulos[] = {"Cod. Producto","Cantidad","Descripcion","Precio Unit.","Sub-Total"};
        m= (DefaultTableModel) jTProducto.getModel();
        m.setColumnIdentifiers(titulos);
        r=db.Listar("Id_presupuesto", "presupuesto", " order by Id_presupuesto ASC");
        try {
            
            if(r.last())
            nro = Integer.valueOf(r.getString(1))+1;
            if(nro>0 && nro <=9){
                jTNumPresup.setText("0000000"+nro);
            }
            if(nro>=10 && nro<=99){
                jTNumPresup.setText("000000"+nro);
            }
            if(nro>=100 && nro<=999){
                jTNumPresup.setText("00000"+nro);
            }
            if(nro>=1000 && nro<=9999){
                jTNumPresup.setText("0000"+nro);
            }
            if(nro>=10000 && nro<=99999){
                jTNumPresup.setText("000"+nro);
            }
            if(nro>=100000 && nro<=999999){
                jTNumPresup.setText("00"+nro);
            }
            if(nro>=1000000 && nro<=9999999){
                jTNumPresup.setText("0"+nro);
            }
            if(nro>=10000000 && nro<=99999999){
                jTNumPresup.setText(""+nro);
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        prod = new jDProductos(null, true, db,2);
        jBImprimirPresup.setEnabled(false);
    }
   
    
    public void actualizarCombo(){
        try {
            r=null;
            r= db.Listar("*", "cliente", "");
            while(r.next()){
                jcNombre.addItem(r.getString("Nom_cliente")+" ,"+r.getString("Id_cliente"));
            }
            AutoCompleteDecorator.decorate(jcNombre);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    /** This method is called from within the structor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jmborrar = new javax.swing.JMenuItem();
        jPCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBaddCliente = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLidCliente = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jcNombre = new javax.swing.JComboBox();
        jLTipoT = new javax.swing.JLabel();
        jLTipo = new javax.swing.JLabel();
        jPfactura = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTNumPresup = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtdias = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTConfirmación = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTConfNro = new javax.swing.JTextField();
        jPcantidad = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTPrecTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jBImprimirPresup = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBGuardPresup = new javax.swing.JButton();
        jPbotones = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTProducto = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        jmborrar.setText("Eliminar");
        jmborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmborrarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jmborrar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Cliente"));

        jLabel1.setText("Nombre del Cliente:");

        jBaddCliente.setText("Agregar Cliente");
        jBaddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaddClienteActionPerformed(evt);
            }
        });

        jLabel16.setText("ID. Cliente:");

        jLidCliente.setText("Nro");

        jcNombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcNombreItemStateChanged(evt);
            }
        });
        jcNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcNombreActionPerformed(evt);
            }
        });
        jScrollPane2.setViewportView(jcNombre);

        jLTipoT.setText("Tipo Cliente:");

        jLTipo.setText("Nro.");

        javax.swing.GroupLayout jPClienteLayout = new javax.swing.GroupLayout(jPCliente);
        jPCliente.setLayout(jPClienteLayout);
        jPClienteLayout.setHorizontalGroup(
            jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLidCliente))
                .addGap(18, 18, 18)
                .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBaddCliente)
                    .addGroup(jPClienteLayout.createSequentialGroup()
                        .addComponent(jLTipoT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLTipo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPClienteLayout.setVerticalGroup(
            jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jBaddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jLidCliente))
                    .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLTipoT)
                        .addComponent(jLTipo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPfactura.setBorder(javax.swing.BorderFactory.createTitledBorder("Cabecera de Presupuesto"));

        jLabel2.setText("Presupuesto Nro:");

        jLabel3.setText("Fecha:");

        jLabel5.setText("Valido por:");

        jtdias.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtdias.setText("15");
        jtdias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtdiasActionPerformed(evt);
            }
        });

        jLabel18.setText("Días");

        jLabel4.setText("Confirmación de Orden:");

        jLabel6.setText("Confirmación Nro°:");

        javax.swing.GroupLayout jPfacturaLayout = new javax.swing.GroupLayout(jPfactura);
        jPfactura.setLayout(jPfacturaLayout);
        jPfacturaLayout.setHorizontalGroup(
            jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPfacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTNumPresup, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPfacturaLayout.createSequentialGroup()
                        .addComponent(jtdias, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPfacturaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTConfNro, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPfacturaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPfacturaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTConfirmación, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        jPfacturaLayout.setVerticalGroup(
            jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPfacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNumPresup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtdias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel4)
                    .addComponent(jTConfirmación, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTConfNro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPcantidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setText("Precio Total:");

        jTPrecTotal.setText("0");

        jLabel11.setText("Gs.");

        jBImprimirPresup.setText("Imprimir Presupuesto");
        jBImprimirPresup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirPresupActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBGuardPresup.setText("Guardar Presupuesto");
        jBGuardPresup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardPresupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPcantidadLayout = new javax.swing.GroupLayout(jPcantidad);
        jPcantidad.setLayout(jPcantidadLayout);
        jPcantidadLayout.setHorizontalGroup(
            jPcantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPcantidadLayout.createSequentialGroup()
                .addComponent(jBGuardPresup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBImprimirPresup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTPrecTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPcantidadLayout.setVerticalGroup(
            jPcantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcantidadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPcantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBImprimirPresup, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGuardPresup, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPcantidadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPcantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPrecTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        jPbotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPbotones.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        jTProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTProducto.setComponentPopupMenu(jPopupMenu1);
        jTProducto.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTProductoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jTProductoAncestorRemoved(evt);
            }
        });
        jScrollPane4.setViewportView(jTProducto);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search_icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel19.setText("Para agregar productos registrados en base de datos al presupuesto, presionar F4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPfactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addComponent(jPbotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPcantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPbotones, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBaddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaddClienteActionPerformed
            new jDnuevocliente(null, true,db,1).setVisible(true);
            actualizarCombo();

    }//GEN-LAST:event_jBaddClienteActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowClosed

    private void jcNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcNombreActionPerformed

    private void jcNombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcNombreItemStateChanged
        String h = String.valueOf(jcNombre.getSelectedItem());
        jLidCliente.setText(h.substring(h.indexOf(",")+1));
        
        ResultSet Tipo = db.Listar("tipo_cliente", "cliente", "where Id_cliente='"+jLidCliente.getText()+"'");
        try {
            if(Tipo.next()){
               jLTipo.setText(Tipo.getString("tipo_cliente"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jcNombreItemStateChanged

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBImprimirPresupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirPresupActionPerformed
    try{
           r=null;
           r=db.Listar("*", "vistapresupuestoN", "where Id_presupuesto='"+jTNumPresup.getText()+"'");
          

           
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }

      JasperReport reporte;
     JasperPrint reporte_view;
     JRResultSetDataSource jrRS = new JRResultSetDataSource(r);
     //Se crea un objeto HashMap
          HashMap parametros = new HashMap();
          parametros.clear();
          //parametros de entrada
          String Total= NL.Convertir(jTPrecTotal.getText(), true);
          String NumFactura = jTNumPresup.getText();
          Integer SumaTotal = Integer.valueOf(jTPrecTotal.getText());
                    
          parametros.put( "SUMATOTAL", SumaTotal );
     try{
         //direccion del archivo JASPER
          URL  in = this.getClass().getClassLoader().getResource("reportes/PresupuestN.jasper");
          reporte = (JasperReport) JRLoader.loadObject( in );
          
          
          //-----------------------------------
          reporte_view = JasperFillManager.fillReport(reporte, parametros, jrRS);
          JasperViewer ventana = new JasperViewer(reporte_view,false);
          ventana.setTitle("Vista Previa");
          ventana.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);
          this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
          ventana.setVisible(true);
          this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
          
          
	  }catch (JRException E){
              JOptionPane.showMessageDialog(null, E.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
          }
    }//GEN-LAST:event_jBImprimirPresupActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        prod.Lista = new String[300][5];
        prod.tipoCliente=Integer.valueOf(this.jLTipo.getText());
        prod.c=prod.f=0;

        prod.setVisible(true); 
        
        //-------------------------------------------------//
        boolean bandera=false;
        int indice=0;
        for(int h=0;h<prod.f;h++){
          bandera = false;
            Integer precio=0;
            Integer cantidad=0;
            String codigo1="";
            String codigo2="";
             indice = 0;
            
            
            r=null;
            r = db.Listar("*", "producto", "where Cod_inter_producto='"+String.valueOf(prod.Lista[h][0]+"'"));
            String vec[]= new String[5];
            
            int hasta= jTProducto.getRowCount();
            
            
                for (int j=0;j<hasta;j++){
                    bandera=false;
                    codigo1 = String.valueOf(jTProducto.getValueAt(j, 0));
                    codigo2 = String.valueOf(prod.Lista[h][0]);
                    if(codigo1.equals(codigo2)){
                        bandera=true;
                        indice = j;
                        break;
                    }
                    
                }
            
            
            if(bandera==false){
                try {
                    
                        r.next();
                        vec[0]= r.getString("Cod_inter_producto");
                        cantidad = Integer.valueOf(prod.Lista[h][2]);
                        vec[1]= String.valueOf(cantidad);
                        vec[2]= r.getString("Nom_producto")+" "+r.getString("Marca_producto");
                        precio = Integer.valueOf(prod.Lista[h][1]);
                        vec[3]= String.valueOf(precio);
                        vec[4]= String.valueOf(precio*cantidad);
                        m.addRow(vec);
                        total = total + Integer.valueOf(vec[4]);
                        jTPrecTotal.setText(String.valueOf(total));
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
                
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jmborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmborrarActionPerformed
        int total = Integer.valueOf(String.valueOf(jTProducto.getValueAt(jTProducto.getSelectedRow(), 3)));
        int totalto = Integer.valueOf(jTPrecTotal.getText());
        jTPrecTotal.setText(String.valueOf(totalto-total));
        this.total = Integer.valueOf(jTPrecTotal.getText()); 
        m.removeRow(jTProducto.getSelectedRow());
}//GEN-LAST:event_jmborrarActionPerformed

    private void jBGuardPresupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardPresupActionPerformed
        if(jTProducto.getRowCount()>0){
            boolean bandera= true;//controla que la existencia del producto sea mayor o igual a cero
            int ctrl_false = 0;//controla si uno de los booleanos dio false
            int filas = jTProducto.getRowCount();//obtengo las filas de la tabla jtproducto

            if(bandera==true){
                if(db.Altas("presupuesto","", "('"+jTNumPresup.getText()+"','"+jLidCliente.getText()+"','"+jLidCliente.getText()+"','"+(a.getYear()+1900)+"/"+(a.getMonth()+1)+"/"+a.getDate()+"','"+jtdias.getText()+"',NULL,'En Espera','"+jTConfirmación.getText()+"','"+jTConfNro.getText()+"')")){
                
                    for(int j=0; j<filas; j++){
                            db.Altas("detalle_presupuesto", "", "('"+jTNumPresup.getText()+"','"+jTProducto.getValueAt(j, 0) +"','"+jTProducto.getValueAt(j, 1)+"',"+jTProducto.getValueAt(j, 3)+")");
                        
                    }
                    jBImprimirPresup.setEnabled(true);
                    JOptionPane.showMessageDialog(null, "El presupuesto se guardó exitosamente ", "Exito", JOptionPane.INFORMATION_MESSAGE);
                    int respuest2 = JOptionPane.showConfirmDialog(null, "¿Desea imprimir este presupuesto?","Confirmar",JOptionPane.YES_NO_CANCEL_OPTION);
                    if(respuest2==JOptionPane.YES_OPTION){
                        jBImprimirPresupActionPerformed(evt);
                    }
                    int respuest = JOptionPane.showConfirmDialog(null, "¿Desea ralizar otro presupuesto?","Confirmar",JOptionPane.YES_NO_CANCEL_OPTION);
                    if(respuest==JOptionPane.YES_OPTION){
                        this.dispose();
                            new jDnPresupuesto(null, true, db).setVisible(true);
                    }else if (respuest==JOptionPane.NO_OPTION){
                        this.dispose();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Ha ocurrido  un error en el momento de registrar el presupuesto", "Atencion", JOptionPane.INFORMATION_MESSAGE);
                }

            }else{
                jBImprimirPresup.setEnabled(false);                
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Seleccione por lo menos un producto.", "Atención", JOptionPane.WARNING_MESSAGE);
        }
}//GEN-LAST:event_jBGuardPresupActionPerformed

    private void jTProductoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTProductoAncestorAdded
    }//GEN-LAST:event_jTProductoAncestorAdded

    private void jTProductoAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTProductoAncestorRemoved
    }//GEN-LAST:event_jTProductoAncestorRemoved

    private void jtdiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtdiasActionPerformed
        this.jtdias.selectAll();
    }//GEN-LAST:event_jtdiasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                jDnPresupuesto dialog = new jDnPresupuesto(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardPresup;
    private javax.swing.JButton jBImprimirPresup;
    private javax.swing.JButton jBaddCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLTipoT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLidCliente;
    private javax.swing.JPanel jPCliente;
    private javax.swing.JPanel jPbotones;
    private javax.swing.JPanel jPcantidad;
    private javax.swing.JPanel jPfactura;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTConfNro;
    private javax.swing.JTextField jTConfirmación;
    private javax.swing.JTextField jTFecha;
    private javax.swing.JTextField jTNumPresup;
    private javax.swing.JTextField jTPrecTotal;
    private javax.swing.JTable jTProducto;
    private javax.swing.JComboBox jcNombre;
    private javax.swing.JMenuItem jmborrar;
    private javax.swing.JFormattedTextField jtdias;
    // End of variables declaration//GEN-END:variables
}
