/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import clases.DBConnect;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Ever
 */
public class jDNuevoGasto extends javax.swing.JDialog {
    private Image imagen = getToolkit().getImage(getClass().getResource("/imagenes/global2.png"));
    private DefaultTableModel m;
    private DBConnect db;
    private Integer total=0;
    private Date a;
    private ResultSet r;
    
    /**
     * Creates new form jDNuevoGasto
     */
    public jDNuevoGasto(java.awt.Frame parent, boolean modal,DBConnect con) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.db = con;
        jBRegGastos.setEnabled(false);
        prepareTable();
        actualizarCampoCategoria();
        this.a = new Date();
        jXDatePicker1.setDate(a);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPProducto = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTPrecio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jBRegGasto = new javax.swing.JButton();
        jXTCategoria = new org.jdesktop.swingx.JXTextField();
        jLabel1 = new javax.swing.JLabel();
        jTDescCat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBRegGastos = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTGasTotal = new javax.swing.JTextField();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Insertar Categoría de Gasto"));

        jLabel7.setText("Categoría de Gasto:");

        jLabel10.setText("Precio/unid:");

        jTPrecio.setText("0");
        jTPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTPrecioKeyReleased(evt);
            }
        });

        jLabel15.setText("Gs.");

        jBRegGasto.setText("Registrar Gasto");
        jBRegGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegGastoActionPerformed(evt);
            }
        });
        jBRegGasto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBRegGastoKeyReleased(evt);
            }
        });

        jXTCategoria.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jXTCategoriaCaretUpdate(evt);
            }
        });
        jXTCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jXTCategoriaKeyReleased(evt);
            }
        });

        jLabel1.setText("Descripción de Categoría:");

        jTDescCat.setEnabled(false);
        jTDescCat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTDescCatKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPProductoLayout = new javax.swing.GroupLayout(jPProducto);
        jPProducto.setLayout(jPProductoLayout);
        jPProductoLayout.setHorizontalGroup(
            jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBRegGasto)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPProductoLayout.createSequentialGroup()
                        .addComponent(jXTCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTDescCat, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                    .addGroup(jPProductoLayout.createSequentialGroup()
                        .addComponent(jTPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        jPProductoLayout.setVerticalGroup(
            jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jXTCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jTDescCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jBRegGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Categoría", "Categoría", "Gasto"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBRegGastos.setText("Guardar Gastos");
        jBRegGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegGastosActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");

        jLabel4.setText("Gasto Total:");

        jTGasTotal.setText("0");

        jXDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha:");

        jLabel2.setText("Gs.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBRegGastos)
                        .addGap(18, 18, 18)
                        .addComponent(jBCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTGasTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTGasTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jBRegGastos)
                    .addComponent(jBCancelar)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public final void prepareTable(){
       m= new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Categoría", "Categoría", "Gasto"
            }
            );
       jTable1.setModel(m);
    }
    
    public final void actualizarCampoCategoria(){
     
        List<String> lista = new ArrayList<String>();
        try {
           ResultSet rs=null;
            rs= db.Listar("Nom_categoria", "categoria", "");
            while(rs.next()){
                lista.add(rs.getString(1));
            }
            AutoCompleteDecorator.decorate(jXTCategoria,lista,false);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error Al acceder a la base de datos",JOptionPane.ERROR_MESSAGE);
        }
        
    }
    private void jTPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTPrecioKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jBRegGastoActionPerformed(null);
            jXTCategoria.requestFocus();
        }
    
    }//GEN-LAST:event_jTPrecioKeyReleased

    private void jBRegGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegGastoActionPerformed
        ResultSet rs=null;
        boolean bandera=false; // informa acerca de la existencia o no de un item igual en la tabla
        String cod1;
        String cod2;
        int indice=0;
        if(!jXTCategoria.getText().equals("")){
           jBRegGastos.setEnabled(true);
           rs= db.Listar("*", "categoria", "where Nom_categoria='"+jXTCategoria.getText()+"'");
           String vec[] = new String[3];
           
           int hasta = jTable1.getRowCount();
           
           for(int i=0;i<hasta;i++){
               bandera=false;
               cod1 = String.valueOf(jTable1.getValueAt(i, 1));
               cod2 = jXTCategoria.getText();
               if(cod1.equals(cod2)){
                   bandera=true;
                   indice = i;
                   break;
               }
           }
           //si la categoria no se ha registrado aún en el gasto actual
           if(!bandera){
               try {
                   //se verifica si esta categoría ya esta registrada en la base de datos
                   if(rs.next()){
                       //si ya se había guardado antes, entonces sólo se agrega
                       //la categoria al gasto actual
                       vec[0]= rs.getString("Id_categoria");
                       vec[1]= rs.getString("Nom_categoria");
                       vec[2]= jTPrecio.getText();
                       
                       m.addRow(vec);
                       total=total + Integer.valueOf(jTPrecio.getText());
                       jTGasTotal.setText(String.valueOf(total));
                       actualizarCampoCategoria();
                   }
               } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane,ex.getMessage(), "Error Al acceder a la base de datos", JOptionPane.ERROR_MESSAGE);
               }
           }else{
               //si la categoría ya se había registrado en el gasto actual
               total=total+Integer.valueOf(jTPrecio.getText());
               jTGasTotal.setText(String.valueOf(total));
               jTable1.setValueAt(String.valueOf(Integer.valueOf(jTPrecio.getText())+Integer.valueOf((String) jTable1.getValueAt(indice,2))),indice, 2);
           }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Debe introducir el nombre de categoria de gasto", "Atención", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBRegGastoActionPerformed

    private void jBRegGastoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBRegGastoKeyReleased
        
    }//GEN-LAST:event_jBRegGastoKeyReleased

    private void jXTCategoriaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jXTCategoriaCaretUpdate
        if(jXTCategoria.getText().equals("")){
            jBRegGasto.setEnabled(false);
        }else{
            jBRegGasto.setEnabled(true);
        }
    }//GEN-LAST:event_jXTCategoriaCaretUpdate

    private void jXTCategoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jXTCategoriaKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            ResultSet rs = db.Listar("Desc_categoria", "categoria", "where  Nom_categoria='"+jXTCategoria.getText()+"'");
            try {
                if(rs.next()){
                    jTDescCat.setText(rs.getString(1));
                }else{
                    String desc = JOptionPane.showInputDialog(rootPane, "Descripción de Categoría", "Categoria", JOptionPane.QUESTION_MESSAGE);
                    db.Altas("categoria", "(Nom_categoria,Desc_categoria)", "('"+jXTCategoria.getText()+"','"+desc+"')");
                    jTDescCat.setText(desc);
                    jTDescCat.requestFocus();
                }
            } catch (SQLException ex) {
                Logger.getLogger(jDNuevoGasto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jXTCategoriaKeyReleased

    private void jBRegGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegGastosActionPerformed
        int filas = jTable1.getRowCount();
        String obs = JOptionPane.showInputDialog(rootPane, "Introduzca alguna observación del gasto registrado", "Observación", JOptionPane.QUESTION_MESSAGE);
        
        if(db.Altas("gastos", "(fecha_gasto,obs_gasto)", "('"+(a.getYear()+1900)+"/"+(a.getMonth()+1)+"/"+a.getDate()+"','"+obs+"')")){
            ResultSet rs = db.Listar("Id_gasto", "gastos", "order by Id_gasto ASC");
            String id_gasto="1";
            try {
                if(rs.next()){
                    rs.last();
                    id_gasto= rs.getString(1);
                }
            } catch (SQLException ex) {
                Logger.getLogger(jDNuevoGasto.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(int i=0;i<filas;i++){
                db.Altas("detalle_gasto", "","("+id_gasto+",'"+jTable1.getValueAt(i, 0)+"','"+jTable1.getValueAt(i, 2)+"')");
            }
        }
    }//GEN-LAST:event_jBRegGastosActionPerformed

    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker1ActionPerformed
        a = jXDatePicker1.getDate();
    }//GEN-LAST:event_jXDatePicker1ActionPerformed

    private void jTDescCatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDescCatKeyReleased
        jTPrecio.requestFocus();
    }//GEN-LAST:event_jTDescCatKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDNuevoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDNuevoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDNuevoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDNuevoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jDNuevoGasto dialog = new jDNuevoGasto(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBRegGasto;
    private javax.swing.JButton jBRegGastos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTDescCat;
    private javax.swing.JTextField jTGasTotal;
    private javax.swing.JTextField jTPrecio;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXTextField jXTCategoria;
    // End of variables declaration//GEN-END:variables
}
