/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jDnuevocliente.java
 *
 * Created on 18/08/2012, 02:36:35 PM
 */
package frames;

import clases.DBConnect;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Edgar    
 */
public class jDnuevocliente extends javax.swing.JDialog {
    private String Usuario;
    private String Password;
    private String Host;
    private String Puerto;
    private String Database;
    DBConnect db;
    int i=0;
    int control=0;
Image imagen = getToolkit().getImage(getClass().getResource("/imagenes/global2.png"));

    /** Creates new form jDnuevocliente */
    public jDnuevocliente(java.awt.Frame parent, boolean modal,DBConnect con,int a) {
        super(parent, modal);
        initComponents();
        this.setIconImage(imagen);
        this.setTitle("Nuevo Cliente");
        this.setLocationRelativeTo(null);
        this.Usuario = con.getUser();
        this.Password = con.getPass();
        db= new DBConnect();
        db.conectado(Usuario, Password);
        setIconImage(imagen);
        control=a;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPformulario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTRUC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JTNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTDireccionEnv = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTPais = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTContacto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCBTipCliente = new javax.swing.JComboBox();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jBCancelar = new javax.swing.JButton();
        jBAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPformulario.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Cliente"));
        jPformulario.setLayout(new java.awt.GridLayout(9, 2, 10, 15));

        jLabel3.setText("C.I O RUC :");
        jPformulario.add(jLabel3);

        jTRUC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTRUCKeyReleased(evt);
            }
        });
        jPformulario.add(jTRUC);

        jLabel1.setText("Nombre :");
        jPformulario.add(jLabel1);

        JTNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTNombreKeyReleased(evt);
            }
        });
        jPformulario.add(JTNombre);

        jLabel5.setText("Direccion :");
        jPformulario.add(jLabel5);

        jTDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTDireccionKeyReleased(evt);
            }
        });
        jPformulario.add(jTDireccion);

        jLabel4.setText("Telefono :");
        jPformulario.add(jLabel4);

        jTTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTTelefonoKeyReleased(evt);
            }
        });
        jPformulario.add(jTTelefono);

        jLabel6.setText("Direccion de Envío:");
        jPformulario.add(jLabel6);

        jTDireccionEnv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTDireccionEnvKeyReleased(evt);
            }
        });
        jPformulario.add(jTDireccionEnv);

        jLabel9.setText("País:");
        jPformulario.add(jLabel9);
        jPformulario.add(jTPais);

        jLabel7.setText("E-Mail:");
        jPformulario.add(jLabel7);
        jPformulario.add(jTEmail);

        jLabel2.setText("Contacto :");
        jPformulario.add(jLabel2);

        jTContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTContactoKeyReleased(evt);
            }
        });
        jPformulario.add(jTContacto);

        jLabel8.setText("Tipo Cliente:");
        jPformulario.add(jLabel8);

        jCBTipCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        jCBTipCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipClienteActionPerformed(evt);
            }
        });
        jPformulario.add(jCBTipCliente);

        jXLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Clientes_32x32.png"))); // NOI18N

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBAceptar.setText("Guardar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPformulario, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPformulario, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar)
                    .addComponent(jBAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.dispose();
                 
        
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        if(!jTRUC.equals("")){
            if(!JTNombre.equals("")){
                if(db.Altas("cliente", "","('"+jTRUC.getText()+"','"+JTNombre.getText()+"','"+jTDireccion.getText()+"','"+jTTelefono.getText()+"','"+jTDireccionEnv.getText()+"','"+jTPais.getText()+"','0','"+jTEmail.getText()+"','"+jTContacto.getText()+"','"+jCBTipCliente.getSelectedItem().toString()+"');"))
                    JOptionPane.showMessageDialog(rootPane, "El cliente ha sido registrado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un error inesperado. Contacte con el Administrador del Sistema", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "El campo Nombre no debe estar vacío","Atencion",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "El campo Ruc no debe estar vacío","Atencion",JOptionPane.ERROR_MESSAGE);
        }
        int resp = JOptionPane.showConfirmDialog(rootPane, "¿Desea terminar el registro de clientes?", "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(resp==JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_jBAceptarActionPerformed

    private void JTNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTNombreKeyReleased
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_JTNombreKeyReleased

    private void jTContactoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTContactoKeyReleased
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_jTContactoKeyReleased

    private void jTRUCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTRUCKeyReleased
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_jTRUCKeyReleased

    private void jTTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTTelefonoKeyReleased
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_jTTelefonoKeyReleased

    private void jTDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDireccionKeyReleased
        if(evt.getKeyCode()== KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_jTDireccionKeyReleased

    private void jTDireccionEnvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDireccionEnvKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDireccionEnvKeyReleased

    private void jCBTipClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                jDnuevocliente dialog = new jDnuevocliente(null, true,null,0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTNombre;
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JComboBox jCBTipCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPformulario;
    private javax.swing.JTextField jTContacto;
    private javax.swing.JTextField jTDireccion;
    private javax.swing.JTextField jTDireccionEnv;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTPais;
    private javax.swing.JTextField jTRUC;
    private javax.swing.JTextField jTTelefono;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    // End of variables declaration//GEN-END:variables
}
