/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jDVentas.java
 *
 * Created on 11/08/2012, 03:10:32 PM
 */
package frames;

import clases.DBConnect;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JOptionPane;
import java.net.URL;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Edgar
 */
public class jDVentas extends javax.swing.JDialog {
   private static String vend;
   Image imagen = getToolkit().getImage(getClass().getResource("/imagenes/global2.png"));
   DBConnect bd;
   DefaultTableModel m;
   ResultSet r;
   private int i=0;
   private String hoy1;
   private String fecha1;
   Date hoy;
   Date fecha;
   DateFormat hola;
   
    /** Creates new form jDVentas */
    public jDVentas(java.awt.Frame parent, boolean modal, DBConnect con) {
        super(parent, modal);
        initComponents();
        setIconImage(imagen);
        this.setLocationRelativeTo(null);
        this.setTitle("Ventas");
        hoy= new Date();
        hola = DateFormat.getDateInstance();
        hoy1 = hola.format(hoy);
        fecha = new Date();
        jXhasta.setDate(hoy);
        fecha.setMonth(hoy.getMonth()-1);
        jXdesde.setDate(fecha);
        bd = con;
        jBNueva.requestFocus();
        PrepararTabla();
        
        
    }
  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpmVenta = new javax.swing.JPopupMenu();
        jmVisualizarVenta = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTVentas = new javax.swing.JTable();
        jPBotones = new javax.swing.JPanel();
        jBNueva = new javax.swing.JButton();
        jBImpreg = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jXhasta = new org.jdesktop.swingx.JXDatePicker();
        jXdesde = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTUtilidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTBusqueda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTDeudaTotal = new javax.swing.JTextField();

        jmVisualizarVenta.setText("Visualizar Venta");
        jmVisualizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmVisualizarVentaActionPerformed(evt);
            }
        });
        jpmVenta.add(jmVisualizarVenta);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTVentas.setComponentPopupMenu(jpmVenta);
        jTVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTVentas);

        jPBotones.setLayout(new java.awt.GridLayout(1, 3));

        jBNueva.setText("Nueva Venta");
        jBNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevaActionPerformed(evt);
            }
        });
        jPBotones.add(jBNueva);

        jBImpreg.setText("Imprimir el registro");
        jBImpreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImpregActionPerformed(evt);
            }
        });
        jPBotones.add(jBImpreg);

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        jPBotones.add(jBSalir);

        jXhasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXhastaActionPerformed(evt);
            }
        });

        jXdesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXdesdeActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Visualizar las ventas correspondientes al periodo");

        jLabel2.setText("de:");

        jLabel3.setText("al:");

        jTUtilidad.setEditable(false);
        jTUtilidad.setText("0");

        jLabel4.setText("Utilidad Total:");

        jLabel5.setText("Gs.");

        jTBusqueda.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTBusquedaCaretUpdate(evt);
            }
        });
        jTBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBusquedaActionPerformed(evt);
            }
        });

        jLabel6.setText("Buscar:");

        jLabel7.setText("Total de Venta:");

        jTTotal.setEditable(false);
        jTTotal.setText("0");

        jLabel8.setText("Gs.");

        jLabel9.setText("Deuda Credito");

        jTDeudaTotal.setEditable(false);
        jTDeudaTotal.setText("0");
        jTDeudaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDeudaTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTBusqueda)
                        .addGap(402, 402, 402))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jXdesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jXhasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(165, 165, 165))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTDeudaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jXhasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jXdesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)
                        .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTDeudaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevaActionPerformed
        // TODO add your handling code here:
        
        new jDnventa(null, true, bd).setVisible(true);
        PrepararTabla();
        
    }//GEN-LAST:event_jBNuevaActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowClosed

    private void jXdesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXdesdeActionPerformed
        // TODO add your handling code here:
        fecha= jXdesde.getDate();
        PrepararTabla();
    }//GEN-LAST:event_jXdesdeActionPerformed

    private void jXhastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXhastaActionPerformed
        // TODO add your handling code here:
        hoy= jXhasta.getDate();
        PrepararTabla();
    }//GEN-LAST:event_jXhastaActionPerformed

    private void jTVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTVentasMouseClicked
        if(evt.getClickCount()==2){
        }
        if(evt.getButton()==evt.BUTTON3){
        }
    }//GEN-LAST:event_jTVentasMouseClicked

    private void jBImpregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImpregActionPerformed
         try{
           r=null;
            r = bd.Listar("*", "vistaventa", "where `Fecha_venta` >= '"+(fecha.getYear()+1900)+"-"+(fecha.getMonth()+1)+"-"+(fecha.getDate())+"' and Fecha_venta <= '"+(hoy.getYear()+1900)+"-"+(hoy.getMonth()+1)+"-"+(hoy.getDate())
                +"'"+"and  (Id_venta like \"%"+jTBusqueda.getText()+"%\" or Nom_cliente like \"%"+jTBusqueda.getText()+"%\" or tipo_venta like \"%"+jTBusqueda.getText()+"%\") order by Id_venta ASC");
          

           
        } catch (Exception ex) {
             //Logger.getLogger(ciudad.class.getName()).log(Level.SEVERE, null, ex);
        }

        JRResultSetDataSource jrRS = new JRResultSetDataSource(r);
        HashMap parameters = new HashMap();
        
        try{
            URL urlMaestro = getClass().getClassLoader().getResource("reportes/report4.jasper");
            // Cargamos el reporte
            JasperReport masterReport = null;
            masterReport = (JasperReport) JRLoader.loadObject(urlMaestro);
            JasperPrint masterPrint = null;
            masterPrint = JasperFillManager.fillReport(masterReport,parameters,jrRS);
               
            
             JasperViewer ventana = new JasperViewer(masterPrint,false);
            ventana.setTitle("Vista Previa");
            ventana.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);
            ventana.setVisible(true);

        }catch(JRException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocurrio un error "+e.toString(),"ATENCION ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBImpregActionPerformed

    private void jmVisualizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmVisualizarVentaActionPerformed
        new jDVistaVenta(null, true,this.bd,String.valueOf(jTVentas.getValueAt(jTVentas.getSelectedRow(), 0))).setVisible(true);
    }//GEN-LAST:event_jmVisualizarVentaActionPerformed

    private void jTBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBusquedaActionPerformed

    private void jTBusquedaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTBusquedaCaretUpdate
        PrepararTabla();
    }//GEN-LAST:event_jTBusquedaCaretUpdate

    private void jTDeudaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDeudaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDeudaTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                jDVentas dialog = new jDVentas(null, true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBImpreg;
    private javax.swing.JButton jBNueva;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPBotones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTBusqueda;
    private javax.swing.JTextField jTDeudaTotal;
    private javax.swing.JTextField jTTotal;
    private javax.swing.JTextField jTUtilidad;
    private javax.swing.JTable jTVentas;
    private org.jdesktop.swingx.JXDatePicker jXdesde;
    private org.jdesktop.swingx.JXDatePicker jXhasta;
    private javax.swing.JMenuItem jmVisualizarVenta;
    private javax.swing.JPopupMenu jpmVenta;
    // End of variables declaration//GEN-END:variables

   
    public String quitarPuntos(String campo){
        String ahora="";
        for(int k =0; k<campo.length();k++){
            if(campo.charAt(k)!='.'){
                ahora =ahora + campo.charAt(k);
            }
        }
        return (ahora);
        
    }
    
    private Integer CalcUtilidad(String Cod){
       ResultSet rS=null;
       rS= bd.Listar("*", "vistafactura", "where Id_venta='"+Cod+"'");
       Integer utilidad=0;
       String filas[]= new String[4];
        try {
            while(rS.next()){
                ResultSet rCostoProd = bd.Listar("pre_compra", "producto", "where Cod_inter_producto='"+rS.getString("Cod_inter_producto")+"'");
                rCostoProd.next();
                filas[0]= rS.getString("Cant_vendida");
                filas[1]=rS.getString("Pre_n_venta");
                filas[2]= String.valueOf(Integer.valueOf(filas[0])*Integer.valueOf(filas[1]));
                filas[3]= String.valueOf(Integer.valueOf(filas[2])-Integer.valueOf(filas[0])*Integer.valueOf(quitarPuntos(rCostoProd.getString(1))));
                utilidad+=Integer.valueOf(filas[3]);
                
            }
         
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,ex.getMessage(),"Error 382", JOptionPane.ERROR_MESSAGE);
        }
        return utilidad;
   }
    private Integer CalcTotal(String Cod){
       ResultSet rS=null;
       rS= bd.Listar("*", "vistafactura", "where Id_venta='"+Cod+"'");
       
       Integer total=0;
       String filas[]= new String[3];
        try {
            while(rS.next()){
                filas[0]= rS.getString("Cant_vendida");
                filas[1]=rS.getString("Pre_n_venta");
                filas[2]= String.valueOf(Integer.valueOf(filas[0])*Integer.valueOf(filas[1]));
                total+=Integer.valueOf(filas[2]);
                
            }
         
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,ex.getMessage(),"Error 382", JOptionPane.ERROR_MESSAGE);
        }
        return total;
   }
    private void PrepararTabla() {
        int utilidadTotal=0;
        int total=0;
        int deudaTotal = 0;
        r= null;
        r = bd.Listar("*", "vistaventa", "where `Fecha_venta` >= '"+(fecha.getYear()+1900)+"-"+(fecha.getMonth()+1)+"-"+(fecha.getDate())+"' and Fecha_venta <= '"+(hoy.getYear()+1900)+"-"+(hoy.getMonth()+1)+"-"+(hoy.getDate())
                +"'"+"and  (Id_venta like \"%"+jTBusqueda.getText()+"%\" or Nom_cliente like \"%"+jTBusqueda.getText()+"%\" or tipo_venta like \"%"+jTBusqueda.getText()+"%\") order by Id_venta ASC");
        
        m= (new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"Cod. venta","Cond. de Venta","Fecha","Nom. Cliente","Observaciones","Utilidad","Venta Total"})
             {
                 boolean[] canEdit = new boolean [] {false,false, false, false, false,false,false};

                 public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }});
        jTVentas.setModel(m);
        String Fila[]= new String[7];
            try {
                while(r.next()){
                    Fila[0]= r.getString("id_venta");
                    Fila[1]= r.getString("tipo_venta");
                    Fila[2]= r.getString("fecha_venta");
                    Fila[3]= r.getString("nom_cliente");
                    Fila[4]= r.getString("observacion");
                    Fila[5] = r.getString("utilidad");
                    Fila[6] = r.getString("total");
                    m.addRow(Fila);
                    utilidadTotal+=Integer.valueOf(Fila[5]);
                    total+=Integer.valueOf(Fila[6]);
                    if(!Fila[1].equals("Contado")){
                        deudaTotal += Integer.valueOf(Fila[6])-Integer.valueOf(r.getString("pagado"));
                    }
                }
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, ex.getMessage(),"Error1",JOptionPane.ERROR_MESSAGE);
            }
            
            jTUtilidad.setText(String.valueOf(utilidadTotal));
            jTTotal.setText(String.valueOf(total));
            jTDeudaTotal.setText(String.valueOf(deudaTotal));
        }
    }

